apache/pekko-connectors

- .asf.yaml
Same as: https://github.com/apache/incubator-pekko/commit/f209e3b19cf3ec718973a536dd32c81de8dd890b
> Divert GitHub notifications

- .github/workflows/link-validator.yml
* the current yml - with everything commented out - is failing on every run and causing a lot of noise
* eg https://github.com/apache/incubator-pekko-connectors/actions/runs/3878566368
* better to run something and re-enable the rest when we're ready
> non empty link-validator.yml

- CONTRIBUTING.md
- LICENSE
- NOTICE
- README.md
- contributor-advice.md
* temporarily drop the MiMa section
> update contributing doc

- .github/workflows/license-and-vulnerabilities.yml
* not currently working
* will need to revisit
* disable to reduce build noise in the interim
> disable fossa check

- cassandra/src/main/resources/reference.conf
- couchbase/src/main/resources/reference.conf
- google-cloud-bigquery-storage/src/main/resources/reference.conf
- google-cloud-bigquery/src/main/resources/reference.conf
- google-cloud-pub-sub-grpc/src/main/resources/reference.conf
- google-cloud-pub-sub/src/main/resources/reference.conf
- google-cloud-storage/src/main/resources/reference.conf
- google-common/src/main/resources/reference.conf
- google-fcm/src/main/resources/reference.conf
- huawei-push-kit/src/main/resources/reference.conf
- ironmq/src/main/resources/reference.conf
- jms/src/main/resources/reference.conf
- kudu/src/main/resources/reference.conf
- orientdb/src/main/resources/reference.conf
- pravega/src/main/resources/reference.conf
- project/CopyrightHeader.scala
- reference/src/main/resources/application.conf
- s3/src/main/resources/reference.conf
- unix-domain-socket/src/main/resources/reference.conf
relates to https://github.com/apache/incubator-pekko-connectors/issues/28
> add license header to conf files

- .github/workflows/check-build-test.yml
- .github/workflows/license-and-vulnerabilities.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-builds.yml
- .github/workflows/publish.yml
> PR CI run only compiles, ignores actual tests

- .github/workflows/check-build-test.yml
> some plugins do not compile due to missing dependency

- .github/workflows/check-build-test.yml
- .github/workflows/link-validator.yml
- .github/workflows/publish.yml
https://github.com/apache/incubator-pekko-connectors/issues/27
> try to publish to Apache's Nexus server

- build.sbt
- project/Common.scala
- project/MetaInfLicenseNoticeCopy.scala
- project/plugins.sbt
trying to fix jar publish still - follow up to #51
> try to use sbt-apache-plugin

- build.sbt
- project/Common.scala
Fixes the issue with publishing locally
> Set dynverSonatypeSnapshots to fix snapshot version

- .github/workflows/publish-nightly.yml
Don't publish jars after every commit.
Run once a day.
> Change to publish-nightly

- project/Common.scala
- project/Dependencies.scala
- scripts/link-validator.conf
Update to latest scala versions
> Update scala versions

- pravega/src/main/scala/org/apache/pekko/stream/connectors/pravega/PravegaSettings.scala
* only 1 entry that seems to need updating
> updated deprecated version to highlight that version is an Alpakka version

- project/Dependencies.scala
Needed for https://github.com/apache/incubator-pekko-projection/pull/19
> Update pekko http version

- project/Dependencies.scala
follow up to https://github.com/apache/incubator-pekko/pull/273
> jackson 2.14.2

- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
As mentioned in the removed TODO, this PR is improving the performance of `createStringCollectionWithMinChunkSizeRec` by keeping track of the current chunk size. This was causing problems running the tests against S3 because the current implementation was converting the entire data structure to an array and recounting it.
> Improve performance of S3 ByteString test generators

- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
Not exactly sure how these S3 tests originally worked (may have been due to specifics of how the buckets were manually created in S3 accounts) but in my ongoing integration with S3 CI work these tests are not passing correctly because the attributes are not correctly being propagated.
> Correctly propagate S3 attributes in tests

- project/Dependencies.scala
see https://github.com/apache/incubator-pekko/pull/317
this PR needs to wait until the scala/pekko compat changes are done
> Jackson 2.14.3

- .github/actions/sync-nightlies/action.yml
- .github/workflows/publish-nightly.yml
Taken from pekko-management which is published https://github.com/apache/incubator-pekko-management/blob/main/.github/workflows/publish-nightly.yml#L40-L61
> Publish nightly docs

- project/Dependencies.scala
these jars support scala 3 (as a bonus)
> upgrade pekko libs and aws lib

- dynamodb/src/test/scala/docs/scaladsl/ExampleSpec.scala
- dynamodb/src/test/scala/docs/scaladsl/RetrySpec.scala
- influxdb/src/test/scala/docs/scaladsl/InfluxDbSourceSpec.scala
Something that I quickly noticed, death to the semicolons
> Remove redundant semicolons

- project/Dependencies.scala
> upgrade pekko-http-circe

- project/Common.scala
> fix issue with URL used for API docs

- project/Dependencies.scala
this jar is recommended in https://lists.apache.org/thread/ln8o1rxmmkz61w5kd8ndh57vqf3omxdh
> test with Scala 3 friendly pekko-connectors-kafka jar

- azure-storage-queue/src/main/scala/org/apache/pekko/stream/connectors/azure/storagequeue/impl/AzureQueueSourceStage.scala
- cassandra/src/test/scala/org/apache/pekko/stream/connectors/cassandra/javadsl/CassandraSessionSpec.scala
- cassandra/src/test/scala/org/apache/pekko/stream/connectors/cassandra/scaladsl/CassandraSessionPerformanceSpec.scala
- project/Dependencies.scala
2 more connectors with scala 3 support
#126
> More scala3 work (cassandra / azure)

- project/Dependencies.scala
- unix-domain-socket/src/main/scala/org/apache/pekko/stream/connectors/unixdomainsocket/impl/UnixDomainSocketImpl.scala
- unix-domain-socket/src/main/scala/org/apache/pekko/stream/connectors/unixdomainsocket/scaladsl/UnixDomainSocket.scala
> support scala3 on unix-domain connector

- google-cloud-bigquery-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/storage/javadsl/BigQueryArrowStorage.scala
- google-cloud-bigquery-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/storage/javadsl/BigQueryAvroStorage.scala
> fix cases where function calls itself (bigquery connector)

- google-cloud-bigquery-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/storage/scaladsl/GrpcBigQueryStorageReader.scala
- google-cloud-bigquery-storage/src/test/scala/docs/scaladsl/ExampleReader.scala
- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/ExampleApp.scala
- google-cloud-pub-sub/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/Formats.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/WithMaterializerGlobal.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2Spec.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/auth/OAuth2CredentialsSpec.scala
- google-fcm/src/test/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/v1/impl/FcmSenderSpec.scala
- project/Dependencies.scala
small compile problem in one class (scala 3 only)
needed to add back some code accidentally reverted in https://github.com/apache/incubator-pekko-connectors/commit/8674ff591172b62986617d6eb61a4ff43a92d417
> support scala3 for google-cloud-storage connector

- build.sbt
See https://github.com/apache/incubator-pekko/pull/271#issuecomment-1596131473
> Removes semver

- docs/src/main/paradox/examples/elasticsearch-samples.md
- docs/src/main/paradox/examples/ftp-samples.md
- docs/src/main/paradox/examples/index.md
- docs/src/main/paradox/examples/jms-samples.md
- docs/src/main/paradox/examples/mqtt-samples.md
- docs/src/main/paradox/kinesis.md
- file/src/main/java/org/apache/pekko/stream/connectors/file/impl/FileTailSource.java
- file/src/main/java/org/apache/pekko/stream/connectors/file/javadsl/FileTailSource.java
- google-cloud-storage/src/test/scala/docs/scaladsl/GCStorageSourceSpec.scala
- ironmq/src/main/scala/org/apache/pekko/stream/connectors/ironmq/impl/IronMqClient.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/JmsProducerStage.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
- slick/src/main/scala/org/apache/pekko/stream/connectors/slick/scaladsl/Slick.scala
- slick/src/test/scala/docs/scaladsl/SlickSpec.scala
* we haven't yet rewritten https://github.com/apache/incubator-pekko-connectors-samples/ but it is better to link here than to akka.io
* with the Kinesis alternatives, I've logged issues in those projects
* https://github.com/500px/kinesis-stream/issues/15
* https://github.com/StreetContxt/kcl-akka-stream/issues/191
> more pekko branding

- avroparquet/src/test/scala-2/docs/scaladsl/AbstractAvroParquet.scala
- avroparquet/src/test/scala-3/docs/scaladsl/AbstractAvroParquet.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/jwt/JwtSprayJson.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/GraphStageCompanion.scala
* relates to https://github.com/apache/incubator-pekko-connectors/pull/178
* the scala3 branch has some files that are not in main branch and this PR fixes those up
> use LEGAL-626 apache header

- build.sbt
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/jwt/JwtSprayJson.scala
- legal/StandardLicense.txt
- project/MetaInfLicenseNoticeCopy.scala
> acknowledge use of jwt-scala code

- huawei-push-kit/src/test/scala/org/apache/pekko/stream/connectors/huawei/pushkit/HmsSettingsSpec.scala
- project/CopyrightHeader.scala
- project/MetaInfLicenseNoticeCopy.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/TestUtils.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/Generators.scala
Same as https://github.com/apache/incubator-pekko/pull/474 but for this repo
> Apply normal apache header new files

- project/Dependencies.scala
> Scalatest 3.2.14

- project/Dependencies.scala
- project/plugins.sbt
* and snapshots updated to versions that were built with pekko 1.0.0
* ideally needs https://github.com/mdedetrich/pekko-streams-circe/pull/4 too
> pekko 1.0.0

- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
and update other jars that need updating because of pekko-http release
> pekko-http 1.0.0

- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-nightly.yml
- docs/src/main/paradox/other-docs/snapshots.md
- docs/src/main/paradox/release-notes/index.md
there might still be a few more changes before we release - this is just an initial set of changes
> update release notes (1.0.0)

- docs/src/main/paradox/release-notes/index.md
- project/Dependencies.scala
> Upgrade protobuf java due to CVEs

- docs/src/main/paradox/overview.md
not rendering well in https://pekko.apache.org/docs/pekko-connectors/current//overview.html#contributing
> broken link in overview.md

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
> Add TODO note for Scala 3 workaround

- build.sbt
- docs/src/main/paradox/geode.md
- geode/src/main/scala-2/org/apache/pekko/stream/connectors/geode/impl/pdx/ObjectDecoder.scala
- geode/src/main/scala-2/org/apache/pekko/stream/connectors/geode/impl/pdx/ObjectEncoder.scala
- geode/src/main/scala-3/org/apache/pekko/stream/connectors/geode/impl/pdx/LabelledGenericGeneric.scala
- geode/src/main/scala-3/org/apache/pekko/stream/connectors/geode/impl/pdx/ObjectDecoder.scala
- geode/src/main/scala-3/org/apache/pekko/stream/connectors/geode/impl/pdx/ObjectEncoder.scala
- geode/src/main/scala/org/apache/pekko/stream/connectors/geode/impl/pdx/PdxDecoder.scala
- geode/src/main/scala/org/apache/pekko/stream/connectors/geode/impl/pdx/PdxEncoder.scala
- geode/src/test/scala/org/apache/pekko/stream/connectors/geode/impl/pdx/PdxWriterMock.scala
- project/Dependencies.scala
tbd
Resolves: https://github.com/apache/incubator-pekko-connectors/issues/152
> Add Scala3 support for Geode

- docs/src/main/paradox/release-notes/index.md
> Geode supports Scala 3

- docs/src/main/paradox/release-notes/index.md
> Add FTP connector setting TrustManager/KeyManager in release notes

- slick/src/test/java/docs/javadsl/DocSnippetFlow.java
- slick/src/test/java/docs/javadsl/DocSnippetFlowWithPassThrough.java
- slick/src/test/java/docs/javadsl/DocSnippetSink.java
- slick/src/test/java/docs/javadsl/DocSnippetSource.java
- slick/src/test/java/docs/javadsl/SlickTest.java
- slick/src/test/scala/docs/scaladsl/DocSnippets.scala
- slick/src/test/scala/docs/scaladsl/SlickSpec.scala
> Remove ALPAKKA from test code

- build.sbt
Was preventing the command from running
> Fix typo in checkCodeStyle

- project/Dependencies.scala
> =sbt Update Scala to 3.3.1

- project/Dependencies.scala
- scripts/link-validator.conf
> Update Scala 2 versions

- CONTRIBUTING.md
- docs/src/main/paradox/pravega.md
- docs/src/main/paradox/spring-web.md
> some lightbend branding

- avroparquet/src/test/java/docs/javadsl/AvroParquetSinkTest.java
- avroparquet/src/test/java/docs/javadsl/Examples.java
- avroparquet/src/test/scala/docs/scaladsl/AbstractAvroParquetBase.scala
- project/Dependencies.scala
https://mvnrepository.com/artifact/org.apache.avro/avro
> upgrade to avro 1.11.3 due to CVE

- google-cloud-bigquery-storage/src/test/java/docs/javadsl/ExampleReader.java
deprecated class - not always needed now
> remove ActorMaterializer

- mqtt-streaming/src/main/scala/org/apache/pekko/stream/connectors/mqtt/streaming/impl/RequestState.scala
> Remove useless condition

- project/Dependencies.scala
https://github.com/qos-ch/logback/issues/745
> logback 1.2.13 (due to cve)

- project/Dependencies.scala
> sshj 0.38.0

- project/Dependencies.scala
> Netty 4.1.104

- build.sbt
- project/plugins.sbt
if I get this merged today, I'll put together a 1.0.2-RC1 for pekko-connectors - I can can do it at the weekend, if not
> use pekko-grpc 1.0.2

- build.sbt
broken because 1.0.2-RC1 is only in staging - this issue is probably going to affect us during every release cycle
> fix mima check

- mqtt-streaming-bench/src/main/scala/org/apache/pekko/stream/connectors/mqtt/MqttPerf.scala
- mqtt-streaming-bench/src/main/scala/org/apache/pekko/stream/connectors/mqtt/streaming/MqttPerf.scala
- project/project-info.conf
the CI issue is down to https://github.com/apache/incubator-pekko-connectors/pull/319
> add ASF headers to old Alpakka files

- NOTICE
- legal/PekkoConnectorsNotice.txt
- legal/S3Notice.txt
see https://github.com/apache/incubator-pekko/pull/1009
> add incubating to NOTICE

- CONTRIBUTING.md
- README.md
also covers https://github.com/apache/incubator-pekko-connectors/issues/320
> add advice on how to run tests

- docs/src/main/paradox/release-notes/index.md
The first line looks strange to me.
> update grammar in release notes

- project/Dependencies.scala
> upgrade to testcontainers 0.41.0

- build.sbt
helps with tracking the CI build and what dependency was used
> add pekko http version logging

- .github/workflows/check-build-test.yml
> run tests on 1.0.x

- .github/workflows/check-build-test.yml
cherry pick 96d7780ebfbbf0c3360a2f81895b092726bf150e #397
> run tests on 1.0.x (#397)

- build.sbt
cherry pick fcf05cb39597267e14cf8234edb2b00f85bcd901 #332
> add pekko http version logging (#332)

- .scala-steward.conf
> upgrade scala steward pins

- project/Dependencies.scala
see #409 
problem started with https://github.com/apache/incubator-pekko-connectors/pull/404/ - I failed to spot the Geode test failures when I merged that
Adding logback dependency fixes the issue
> fix geode test failures

- .github/workflows/check-build-test.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-pekko-1.1-builds.yaml
want to pick up https://github.com/coursier/cache-action/releases/tag/v6.4.5
> update coursier action

- project/plugins.sbt
Co-authored-by: scala-steward-asf[bot] <147768647+scala-steward-asf[bot]@users.noreply.github.com>
(cherry picked from commit 2658681669659618a18261a955ec1c0e4a04650e)
> Update sbt-pekko-build to 0.3.3 (#429)

- project/Dependencies.scala
v2.24 causes issues but this is good enough as a start
https://github.com/apache/incubator-pekko-connectors/pull/380
> influxdb client 2.23

- build.sbt
- project/Dependencies.scala
- solr/src/test/java/docs/javadsl/SolrTest.java
- solr/src/test/scala/docs/scaladsl/SolrSpec.scala
later will upgrade to solr 9 - some compile issues to sort
> upgrade to solr 8

- .github/workflows/check-build-test.yml
- .github/workflows/nightly-pekko-1.1-builds.yaml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-nightly.yml
- .jvmopts
we are getting some build failures but more warnings about GC etc during builds
> increase Xmx in builds

- google-cloud-pub-sub-grpc/src/main/mima-filters/1.1.x.backwards.excludes/google-cloud-pubsub.backwards.excludes
- project/Dependencies.scala
newer versions cause of protobuf compile issues but this version works and improves out dependency situation
> google-cloud-pubsub 1.122.2

- project/Dependencies.scala
* upgrade improves our dependency situation
* newest jars cause us compile issues
> upgrade google-cloud-bigquerystorage

- .github/workflows/check-build-test.yml
- .github/workflows/nightly-pekko-1.1-builds.yaml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-nightly.yml
- .jvmopts
cherry pick dfe15c1e6a158a6387868f0548c123206675d521 #448
> increase Xmx in builds (#448)

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Previously, in this test, the server sent a 'publish' concurrent to the client sending the 'ack' for that publish. This fix makes sure the 'ack' is sent only after observing the 'publish'.
Hopefully fixes #458
This PR still fails due to #454 but #460 suggests it should be OK when combined with #456
> mqtt-streaming: fix flaky 'unsubscribe a client session' test

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
Issue was fixed in Scala 3.3.1, see https://github.com/lampepfl/dotty/issues/18438
> Remove Scala 3 type inference workaround

- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/java/docs/javadsl/DiscoveryTest.java
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSessionExamplesSpec.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSourceSpec.scala
- couchbase/src/test/scala/docs/scaladsl/DiscoverySpec.scala
- couchbase/src/test/scala/org/apache/pekko/stream/connectors/couchbase/testing/CouchbaseSupport.scala
- docker-compose.yml
> Rename akka reference to pekko

- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/java/docs/javadsl/DiscoveryTest.java
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSessionExamplesSpec.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSourceSpec.scala
- couchbase/src/test/scala/docs/scaladsl/DiscoverySpec.scala
- couchbase/src/test/scala/org/apache/pekko/stream/connectors/couchbase/testing/CouchbaseSupport.scala
- docker-compose.yml
(cherry picked from commit 43ee6b702cc1ecbbf23a78d0acd3de957b21add4)
> Rename akka reference to pekko (#467)

- mqtt/src/main/scala/org/apache/pekko/stream/connectors/mqtt/impl/MqttFlowStage.scala
- mqtt/src/main/scala/org/apache/pekko/stream/connectors/mqtt/settings.scala
> mqtt import order

- .scala-steward.conf
- project/Dependencies.scala
Reverts apache/incubator-pekko-connectors#416
* https://github.com/apache/incubator-pekko-connectors/issues/61
* https://github.com/apache/incubator-pekko-connectors/discussions/443
> Revert "Update hbase-common, hbase-shaded-client to 1.7.2"

- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/JmsConnector.scala
- jms/src/test/scala/org/apache/pekko/stream/connectors/jms/JmsConnectionStatusSpec.scala
- jms/src/test/scala/org/apache/pekko/stream/connectors/jms/JmsProducerRetrySpec.scala
- jms/src/test/scala/org/apache/pekko/stream/connectors/jms/JmsSharedServerSpec.scala
- jms/src/test/scala/org/apache/pekko/stream/connectors/jms/JmsSpec.scala
- jms/src/test/scala/org/apache/pekko/stream/connectors/jms/scaladsl/CachedConnectionFactory.scala
- project/Dependencies.scala
> [jms] close sessions when exceptions happen

- project/TestChanged.scala
> remove the unnecessary package import

- project/Dependencies.scala
* build of main branch is broken (CI only) - the build works on my laptop
* I'm not sure if a corrupt version of the jms jar is being used
* none of the recent merges seem to be the cause - I've tried reverting them
> jms build issue

- project/plugins.sbt
Copied working setup from pekko-http build.
See https://github.com/apache/incubator-pekko-connectors/actions/runs/8104621838/job/22151574091
Caused by Java 8 unfriendly jars
> fix nightly doc publish

- .scala-steward.conf
v1.3.x is last version to support java 8
> pin logback

- project/Dependencies.scala
Co-authored-by: scala-steward-asf[bot] <147768647+scala-steward-asf[bot]@users.noreply.github.com>
(cherry picked from commit ba44e705cc292105ff20e31897f5606b937d14ce)
> Update scala-library to 2.13.13 (#517)

- project/Dependencies.scala
Co-authored-by: scala-steward-asf[bot] <147768647+scala-steward-asf[bot]@users.noreply.github.com>
(cherry picked from commit 4a7f9f8007494eda8f3deef519bf1cc129bbd457)
> Update scala3-library to 3.3.3 (#533)

- scripts/link-validator.conf
(cherry picked from commit 663c832341546fe902bf56cbba6c87b0869aef84)
> Update link-validator.conf due to Scala 2.13.13

- project/Dependencies.scala
Co-authored-by: scala-steward-asf[bot] <147768647+scala-steward-asf[bot]@users.noreply.github.com>
Co-authored-by: PJ Fanning <pjfanning@users.noreply.github.com>
(cherry picked from commit ab5e2b61cc512188ded61fb52f8070611ab9874e)
> Update scala-library to 2.12.19 (#516)

- .scala-steward.conf
we are stuck with our current google jars due to breaking changes in newer ones
> pin google jars

- build.sbt
cherry pick 2c69b7edcfcd6bb64b781fb74f61e5562a04d388 #585
> remove incubator footer (#585)

- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/jwt/JwtSprayJson.scala
cherry pick 84947f8d2c1476bb869853ba9d671186e8407755 #607
> update license header (#607)

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- testkit/src/main/scala/org/apache/pekko/stream/connectors/testkit/CapturingAppender.scala
- testkit/src/main/scala/org/apache/pekko/stream/connectors/testkit/scaladsl/LogCapturing.scala
> fix typo for sourceActorSystem and mistake package name

- csv/src/main/scala/org/apache/pekko/stream/connectors/csv/impl/CsvToMapJavaStage.scala
- csv/src/main/scala/org/apache/pekko/stream/connectors/csv/impl/CsvToMapStage.scala
- csv/src/test/scala/docs/scaladsl/CsvToMapSpec.scala
avoids wasteful object creation when we have a constant already
> csv: use ByteString.empty

- .github/workflows/link-validator.yml
always fails - https://github.com/apache/pekko-connectors/actions/workflows/link-validator.yml
> fix link-validator.yml

- LICENSE
- build.sbt
- legal/FTPLicense.txt
- legal/FTPNotice.txt
- project/MetaInfLicenseNoticeCopy.scala
acknowledge new code copied from commons-net - #171
> change FTP license/notice

- project/Dependencies.scala
see https://github.com/apache/pekko-connectors/issues/686
> add scala-reflect dependency to slick connector

- project/Dependencies.scala
see #651 
Parquet 1.14.1 in theory has a fix - https://issues.apache.org/jira/browse/PARQUET-2468
> parquet 1.14.1

- .github/workflows/check-build-test.yml
see https://github.com/apache/pekko-connectors/issues/697
> temporarily disable ironmq tests

- docs/src/main/paradox/aws-shared-configuration.md
- docs/src/main/paradox/dynamodb.md
- dynamodb/src/test/java/docs/javadsl/RetryTest.java
- dynamodb/src/test/scala/docs/scaladsl/RetrySpec.scala
see #707 
fixes a compile issue breaking main build - I would prefer to merge this as opposed to the revert PR #706
> switch to AWS SDK RetryStrategy

- scripts/link-validator.conf
* https://github.com/apache/pekko-projection/pull/183
* https://github.com/apache/pekko-connectors/actions/runs/9738978725
* https://github.com/apache/pekko-connectors/issues/677
> ignore datastax link issues

- build.sbt
Possible alternative to https://github.com/apache/pekko-connectors/pull/713
> fix: disable -Werror for 'file' on Java 21 CI

- unix-domain-socket/src/main/scala/org/apache/pekko/stream/connectors/unixdomainsocket/impl/UnixDomainSocketImpl.scala
Looking at `UnixDomainSocketImpl#outgoingConnection`, the test failure at #462 can/should only happen when both `connectionFlow` and `connectionFinished` complete successfully.
There seems to be potential race between `UnixDomainSocketImpl#connectKey` and `channel.connect` both completing `connectionFinished`, though this seems strange. This PR is meant to add diagnostic logging so next time the test fails we can confirm whether this is indeed what's going on.
> chore: add diagnostics to diagnose UnixDomainSocketSpec

- .scala-steward.conf
- project/Dependencies.scala
revert #750 
see https://github.com/apache/pekko-projection/pull/189
> revert to h2 2.2

- project/Dependencies.scala
(cherry picked from commit eb3ae26572c0659993af51d11ba71c176a81d504)
> Update Pekko Stream Circe to 1.1.0

- project/Dependencies.scala
> pekko-connectors-kafka 1.1.0

- .github/workflows/check-build-test.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-pekko-1.0-builds.yaml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
see https://github.com/apache/pekko-http/pull/619
> CI: setup-sbt

- .github/workflows/check-build-test.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-pekko-1.0-builds.yaml
I spotted these jobs running on my fork
> only run CI jobs on main fork

- .github/workflows/check-build-test.yml
we have [.github/workflows/link-validator.yml](https://github.com/apache/pekko-connectors/blob/bf5545d9b8d916e69c8f98c3c10cc72af364efdf/.github/workflows/link-validator.yml#L35)
> remove TODO in workflow

- .github/workflows/check-build-test.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/format.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-pekko-1.0-builds.yaml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/scala-steward.yml
different headers based on whether the file originates from Akka
> ci: add headers to files

- .scala-steward.conf
https://github.com/sbt/sbt-java-formatter/pull/218
Replaces #1037
> Pin sbt-java-formatter to 0.9.x

- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/scaladsl/GCStorageWiremockBase.scala
(cherry picked from commit 0306dd6739e8e7b26a0d70e5878676ca37ef5eec)
> Fix metadata not working with GCStorage

- .scala-steward.conf
- project/Dependencies.scala
Foe 1.2.0 release, let's upgrade jackson.
> jackson 2.19.0

- project/Dependencies.scala
cherry pick 00fef3b494b604f1a6375fc8381d79db237b1316 #1059
> log4j 2.24.3 (#1059)

- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
- google-common/src/main/mima-filters/1.1.x.backwards.excludes/private-zero-chunk-change.backwards.excludes
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/util/AnnotateLast.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/util/AnnotateLastSpec.scala
(cherry picked from commit 0cc560d725c41fb73f7225ad74311d920246d5fd)
> Make GCS resumableUpload work with empty byte payload

- project/build.properties
Scala Steward hasn't created a PR for this
> sbt 1.11.2

- project/Dependencies.scala
> junit-interface 0.13.3

- .github/workflows/publish-1.2-docs.yml
- docs/src/main/paradox/release-notes/index.md
- docs/src/main/paradox/release-notes/releases-1.1.md
- docs/src/main/paradox/release-notes/releases-1.2.md
also includes forward fit of #1202 
cherry pick 996e699a93c44b1a40e6b2b03954b1a531c123cc
> CI job to publish 1.2.0 release notes

- project/Dependencies.scala
Removed scala-collection-compat dependency from testkit.
> Remove scala-collection-compat from test dependencies

- .scala-steward.conf
> pin activemq (used only in JMS tests)

- google-cloud-bigquery-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/storage/ProtobufConverters.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/StorageObject.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/GoogleSettings.scala
- sse/src/main/scala/org/apache/pekko/stream/connectors/sse/javadsl/EventSource.scala
relates to https://github.com/apache/pekko-grpc/pull/522
> remove unnecessary map calls
