apache/pekko-connectors

- build.sbt
This check is causing sbt to load with the following error
```
[error] Failed to derive version from git tags. Maybe run `git fetch --unshallow`? Derived version: 0.0.0+2675-8c31b4d7-SNAPSHOT
```
Since there aren't any tags in the new incubator-pekko repo. The PR disables the check so that sbt can actually start
> Temporarily disable dynver git tag check

- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
In preparation of applying new scalafmt rules where this PF implementation would fail to parse.
> Update GCS unmarshaller to workaround new scalafmt rules

- .github/workflows/format.yml
- build.sbt
Similar to pekko core, replaces the sbt scalafmt check with a github actions one. Also removes the `scalafmtCheckAll`/`scalafmtSbtCheck` check because it is now unnecessary (and it also doesn't play well with IDE's).
> Add github workflow to check scala code is formatted

- docker-compose.yml
* relates to https://github.com/apache/incubator-pekko-connectors/issues/42
* The datadog/squid image was deleted
* FTP tests passed in https://github.com/apache/incubator-pekko-connectors/actions/runs/4394330140 with this change (in another PR that is not for merging, just for testing)
* failed before this change - https://github.com/apache/incubator-pekko-connectors/actions/runs/4394281553
> ftp CI tests: use ubuntu:squid docker image

- mongodb/src/test/scala/docs/scaladsl/MongoSinkSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
* google-pub-sub has a separate issue
* this covers https://github.com/apache/incubator-pekko-connectors/issues/46
* plus one recent failure in the mongo tests - https://github.com/apache/incubator-pekko-connectors/actions/runs/4416039025/jobs/7741174718
> increase timeouts on flaky tests

- project/Common.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/S3Headers.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/javadsl/S3.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/model.scala
S3 code needs a lot of changes to compile in Scala. 2.12
> Scala2.12 support

- file/src/test/scala/docs/scaladsl/ExecutableUtils.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
Completely removes usages of `Stream`, making https://github.com/apache/incubator-pekko-connectors/issues/71 redudnant.
Resolves: https://github.com/apache/incubator-pekko-connectors/issues/71
> Remove usages of Stream

- file/src/test/scala/docs/scaladsl/ExecutableUtils.scala
- project/Dependencies.scala
Updates Pekko to latest version which brings in the fix for `ByteString`, allowing us to remove the `.toArray` workaround that was introduced in https://github.com/apache/incubator-pekko-connectors/pull/74
> Update pekko and remove ByteString Scala 2.12 workaround

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
So this is a bug which I discovered after I added this feature (https://github.com/akka/alpakka/pull/2899) to Alpakka. I didn't manage to fix this in Alpakka because they changed their license to BSL before I discovered it.
Essentially, if you are using the list buckets call from a configured region that is not `US_EAST_1` it will fail. As noted this only occurs in AWS and not Minio (Minio is a 3rd party implementation of AWS). I have added a test to confirm this behaviour, i.e. if you revert `HttpRequests.listBuckets(s3Headers.headers), Some(Region.US_EAST_1))` to `HttpRequests.listBuckets(s3Headers.headers))` the test will fail. Unfortunately in order to replicate this you need an actual AWS account to test against (I personally used a company test account to verify this).
Regarding …
> Force US_EAST_1 for S3 listBuckets call

- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/MinioContainer.scala
The latest version of Minio seems to have fixed a flaky bug where the container wasn't started even though it reported itself as ready
> Update Minio version to improve flakiness

- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
The fact that these values are set to 4 and 5 in the base test trait is likely complete oversight. For some context, these values are used in the `list with real credentials`, `list with real credentials using the Version 1 API`  and `list with real credentials in non us-east-1 zone` tests. In all of these cases, these are the first tests to run in the test suite and when they do run the buckets are empty which is why 0 is the correct value.
These tests were passing as expected in Minio since they were overridden to be 0 but they were failing in AWS S3.
> Set contentCount values to 0

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
- s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
This PR fixes https://github.com/akka/alpakka/issues/2906, Alpakka created a regression whereby their latest Alpakka BSL release (4.0.0) has multipart upload broken.
According to S3 docs (see https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html#API_CompleteMultipartUpload_Examples), you are not allowed to have any other headers that is not SSE related.
I tested this on my companies S3 account and I can confirm that it passes.
> Only pass SSE headers for multipart upload requests

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/HttpRequests.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/Marshalling.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Request.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/javadsl/S3.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/model.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
So the context behind this PR is that I am trying to get integration tests working against the real AWS S3 (see https://github.com/apache/incubator-pekko-connectors/issues/67) and as part of that integration I am implementing the ability of the test suite to dynamically create/delete buckets (to prevent flaky test issues as a result of concurrency/left over state). In that work I ended up realizing that in order to get some of the tests to work I have to create buckets with versioning hence why I am making this PR.
Slightly annoyingly, the API of https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketVersioning.html / https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketVersioning.html has some unique peculiarities which made it harder to model. For starters the API …
> Add S3 put plus get bucketWithVersioning API

- project/Dependencies.scala
This is likely a result of us not using the pekko/pekko-http versions correctly due to using snapshots but nevertheless its better to pin `pekko-http` to the same version as the other pekko-http artifacts
```
[info]   java.lang.IllegalStateException: You are using version 0.0.0+4338-c98db6bd-SNAPSHOT of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 0.0.0+4338-c98db6bd-SNAPSHOT of the [pekko-http] artifacts to your project. Here's a complete collection of detected artifacts: (0.0.0+4298-26846a02-SNAPSHOT, [pekko-http]), (0.0.0+4338-c98db6bd-SNAPSHOT, [pekko-http-core, pekko-http-spray-json, pekko-parsing]). See also:
```
> Fix dependency resolution with GoogleBigQueryStorage module

- google-cloud-pub-sub/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/GooglePubSubSpec.scala
Resolves: https://github.com/apache/incubator-pekko-connectors/issues/47
Turns out the reason why the tests were failing is because at some point an overloaded method with the `host: Option[String]` parameter was added and its this specific overloaded method which is now being called in the auth tests and the mocks in the broken tests was pointing to the original non overloaded method.
> Fix broken GooglePubSubSpec tests

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
```
[info] - should produce a duplicate publish on the server given two client connections *** FAILED *** (660 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Waited 600 milliseconds. (MqttSessionSpec.scala:2045)
```
from https://github.com/apache/incubator-pekko-connectors/actions/runs/4864707370/jobs/8674075485?pr=92 .
Note that this timeout along with the comment is copied from already existing tests in this spec, specifically https://github.com/apache/incubator-pekko-connectors/blob/c487bc3113edf4c50721ff337b0a9b5cfb492edc/mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala#L521-L522 .
There are other reasons why the mqtt-streaming tests are flaky but this is one of the low hanging fruit reasons.
> Increase timeout for failing mqtt-streaming tests

- mqtt-streaming/src/test/resources/application.conf
Forgot to increase another type of timeout, i.e.
```
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ByteString(50, 26, 0, 10, 115, 111, 109, 101, 45, 116, 111, 112, 105, 99, 0, 1, 115, 111, 109, 101, 45, 112, 97, 121, 108, 111, 97, 100)
```
Lets see if this helps
> Increase expected message timeout for mqtt-streaming

- .github/workflows/nightly-builds.yaml
- project/Dependencies.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/TestUtils.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/Generators.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
Resolves: https://github.com/apache/incubator-pekko-connectors/issues/67
Firstly before reviewing its recommended to change the diff to ignore whitespace i.e. 
as it will make it easier to review.
This PR is about modifying the `AWSS3IntegrationSpec` so that it can run in CI against a real AWS S3 account which Apache INFRA is supporting (see https://issues.apache.org/jira/browse/INFRA-24353). Initially the idea was to do this later, but considering that the Pekko/Akka S3 client unintentionally broke (see https://github.com/apache/incubator-pekko-connectors/pull/81) the importance of this was increased, i.e. we want to make sure that the S3 client actually works whenever a release is made.
Although the current `AWSS3IntegrationSpec` can currently run against a real S3 account it was …
> Integrate AWSS3IntegrationSpec with S3 Account

- .github/workflows/nightly-builds.yaml
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
So if you follow the `#asfinra` slack discussion at https://the-asf.slack.com/archives/CBX4TSBQ8/p1683672460539449 we managed to get most of the AWS S3 tests passing in Apache's S3 account however a few of them turned out to be problematic (see https://github.com/apache/incubator-pekko-connectors/actions/runs/4931691903/jobs/8813985233 for more info). The problematic tests were ones that involved the `ListAllMyBuckets` call + MFA, which is difficult to get right with restricted permissions (necessary for security since this Apache S3 account is being used by others).
This PR makes tests that require these permissions to be configurable as well as disabling them in our nightly CI run. While it may be theoretically possible to come up with an IAM policy to test everything, I don't have …
> Don't run problematic tests in AWS S3 account

- README.md
Now that our nightly builds (currently S3 integration tests) are passing (see https://github.com/apache/incubator-pekko-connectors/actions/runs/4946076457) lets add a badge to illustrate this.
> Add nightly builds badge

- amqp/src/test/scala/org/apache/pekko/stream/connectors/amqp/scaladsl/AmqpConnectorsSpec.scala
- azure-storage-queue/src/test/scala/docs/scaladsl/AzureQueueSpec.scala
- project/CopyrightHeader.scala
- project/Dependencies.scala
Unwraps single string interpolation i.e. `s"${something}"` into `s"$something"`. Make sure to do a rebase merge of this PR because I need to add its commit to `.git-blame-ignore-revs`
> Unwrap single string interpolation syntax

- project/Dependencies.scala
* testkit project is internal
* the logback-classic dependency is duplicated
* logback 1.2.11 is what we use in pekko core when testing
* there are CVEs in logback 1.2.3 -- see https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.3 (transitive dependency on logback-core 1.2.3 is the issue)
> upgrade logback

- .github/workflows/check-build-test.yml
I looked at https://github.com/apache/incubator-pekko-connectors/actions/runs/5114976247/jobs/9196215819?pr=121 and you can note that the Scala 2.12 tests are compiling to target/2.13.
I've changed the build files and using `++2.12.17` works as it should.
> fix issue with Scala 2.12 testing

- dynamodb/src/main/scala/org/apache/pekko/stream/connectors/dynamodb/javadsl/DynamoDb.scala
- elasticsearch/src/main/scala/org/apache/pekko/stream/connectors/elasticsearch/ElasticsearchConnectionSettings.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/javadsl/FtpApi.scala
- google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/PubSubSettings.scala
- google-cloud-pub-sub/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/model.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/GCStorageAttributes.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/GCStorageExt.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/GCStorageSettings.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/StorageSettings.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/javadsl/GCStorage.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/Credentials.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/FcmNotificationModels.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/FcmSettings.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/impl/FcmFlows.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/impl/FcmJsonSupport.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/impl/FcmSender.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/javadsl/GoogleFcm.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/scaladsl/GoogleFcm.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/JmsExceptions.scala
- sse/src/main/scala/org/apache/pekko/stream/connectors/sse/javadsl/EventSource.scala
Pekko Connectors versions will start at 1.0.0 so it will be confusing if we have deprecations that are since '3.0.0'. We need to prefix such version numbers to make it clear they relate to Alpakka releases.
> fix up deprecation versions so they refer to Alpakka

- couchbase/src/main/scala/org/apache/pekko/stream/connectors/couchbase/model.scala
- couchbase/src/main/scala/org/apache/pekko/stream/connectors/couchbase/scaladsl/CouchbaseFlow.scala
- couchbase/src/test/scala/org/apache/pekko/stream/connectors/couchbase/testing/CouchbaseSupport.scala
- project/Dependencies.scala
* I've worked through a couple of compile issues
* play-json (a test dependency) doesn't have a full release that supports Scala 3 and furthermore, the 2.10.0 RCs only support Java 11.
* it was easy to test with jackson instead
* this PR is targeted at the 'scala3' branch
> Scala3 couchbase support

- project/Dependencies.scala
a test only dependency - v5 is scala 3 only but I want to get up to v4 first - and then add logic to use different versions depending on scala version
> avro4s 4.1.1 (test dependency)

- google-cloud-bigquery/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/BigQueryException.scala
- google-cloud-bigquery/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/javadsl/BigQuery.scala
- google-cloud-pub-sub/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/Formats.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/WithMaterializerGlobal.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
- google-common/src/main/java/org/apache/pekko/stream/connectors/google/javadsl/XUploadContentType.java
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/GoogleSettings.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/Credentials.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2Exception.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/http/GoogleHttp.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/javadsl/Google.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/jwt/JwtSprayJson.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/scaladsl/`X-Upload-Content-Type`.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/ResumableUploadSpec.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2Spec.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/auth/OAuth2CredentialsSpec.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/http/GoogleHttpSpec.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/impl/FcmSender.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/v1/impl/FcmSender.scala
- google-fcm/src/test/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/v1/impl/FcmSenderSpec.scala
- huawei-push-kit/src/test/scala/org/apache/pekko/stream/connectors/huawei/pushkit/impl/PushKitSenderSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttActorSystemsSpec.scala
- project/Dependencies.scala
* needed to grab a class from jwt-scala (no longer maintained - spray-json support has been dropped in that project)
* will log an issue to update license to mention the use of this code 
* also updates huawei-push-kit because that has a dependency on the jwt-scala classes - but it turns out it only needs the jwt-json-common instead of the jwt-spray-json
> support scala3 (google-common)

- ironmq/src/main/scala/org/apache/pekko/stream/connectors/ironmq/impl/IronMqClient.scala
- project/Dependencies.scala
As discussed on mailing list (see https://lists.apache.org/thread/qx31xljn6bf7rwcd3kbb9btcdvoxmmwy), replaces the fork of https://github.com/hseeberger/akka-http-json with [pekko-streams-circe](https://github.com/mdedetrich/pekko-streams-circe)
> Use pekko-streams-circe for IronMQ

- build.sbt
- json-streaming/src/main/scala-2/org/apache/pekko/stream/connectors/json/impl/QueueHelper.scala
- json-streaming/src/main/scala-3/org/apache/pekko/stream/connectors/json/impl/QueueHelper.scala
- json-streaming/src/main/scala/org/apache/pekko/stream/connectors/json/impl/JsonStreamReader.scala
- project/Dependencies.scala
Part of https://github.com/apache/incubator-pekko-connectors/issues/126
A strange Scala 3 issue means that immutable.Queue.enqueue(ByteString) won't compile. I tried to produce a minimal case in scastie to report a Scala compiler bug but the minimal case works.
For now, I think using a mutable.Queue is ok and I can log an issue to keep checking when we upgrade Scala 3 to see if the issue is fixed.
> scala 3 support for json streaming

- couchbase/src/main/scala/org/apache/pekko/stream/connectors/couchbase/scaladsl/CouchbaseFlow.scala
- elasticsearch/src/main/scala/org/apache/pekko/stream/connectors/elasticsearch/impl/RestBulkApi.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchConnectorBehaviour.scala
- elasticsearch/src/test/scala/docs/scaladsl/OpensearchConnectorBehaviour.scala
- google-cloud-pub-sub/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/Formats.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/WithMaterializerGlobal.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2Spec.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/auth/OAuth2CredentialsSpec.scala
- google-fcm/src/test/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/v1/impl/FcmSenderSpec.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/GraphStageCompanion.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/JmsAckSourceStage.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/JmsConnector.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/JmsConsumerStage.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/JmsProducerStage.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/JmsTxSourceStage.scala
- jms/src/main/scala/org/apache/pekko/stream/connectors/jms/impl/SourceStageLogic.scala
- project/Dependencies.scala
Part of https://github.com/apache/incubator-pekko-connectors/issues/126
Scala 3 compile issues needed fixing.
* main ones were related to using protected methods on self types
* also some issues where fields were ambiguous (multiple inheritance in Scala means that a field can be declared on 2 separate traits)
I introduced a GraphStageCompanion trait to give public access to the methods that were needed to get Scala3 compile to work.
> Scala3 support for jms connector

- ironmq/src/test/scala/org/apache/pekko/stream/connectors/ironmq/scaladsl/IronMqProducerSpec.scala
- project/Dependencies.scala
> support ironmq on scala3

- project/Dependencies.scala
need newer version of cats-core - as old one does not support scala3
part of #126
> Scala3 hdfs

- mqtt-streaming/src/main/scala/org/apache/pekko/stream/connectors/mqtt/streaming/model.scala
- mqtt-streaming/src/main/scala/org/apache/pekko/stream/connectors/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- project/Dependencies.scala
part of #126 
The main problems
* Scala 3 is stricter about private fields/functions - some tests are in `docs.scaladsl` and somehow Scala 2 lets that have access to private fields - Scala 3 cares about this - I had to make some stuff public and mark them as `@InternalApi`
* MqttFlowSpec had to be changed. Scala 3 does not allow access to some stuff on self types - including implicits
* since it is test code and it was easy to get rid of the self type, that seemed the easiest solution (I had tried a number of other ways without success)
> Scala3 mqtt streaming

- project/Dependencies.scala
- unix-domain-socket/src/main/scala/org/apache/pekko/stream/connectors/unixdomainsocket/impl/UnixDomainSocketImpl.scala
- unix-domain-socket/src/main/scala/org/apache/pekko/stream/connectors/unixdomainsocket/scaladsl/UnixDomainSocket.scala
need to redo https://github.com/apache/incubator-pekko-connectors/pull/155
> support scala3 on unix-domain connector

- project/plugins.sbt
Seems tidiest to upgrade to newer snapshot.
It is contributing to some issues migrating the connectors that need grpc to support scala 3.
> upgrade grpc plugin

- amqp/src/main/scala/org/apache/pekko/stream/connectors/amqp/AmqpConnectionProvider.scala
- project/Dependencies.scala
main issue is that Scala3 is stricter about accessing class fields during recursion
part of #126
> support scala3 for amqp connector

- google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/javadsl/GooglePubSub.scala
- google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/javadsl/GrpcPublisher.scala
- google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/javadsl/GrpcSubscriber.scala
- google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/scaladsl/GrpcPublisher.scala
- google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/scaladsl/GrpcSubscriber.scala
- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
- project/Dependencies.scala
> enable scala3 build for more google connectors

- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpDirectoryOperationsGraphStage.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpGraphStageLogic.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpLike.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/scaladsl/FtpApi.scala
- ftp/src/test/scala/org/apache/pekko/stream/connectors/ftp/BaseSpec.scala
- project/Dependencies.scala
> Scala3 ftp support

- project/Dependencies.scala
part of #126 
* most of the work has been done in other PRs
* this just enables the scala3 build for couchbase, cassandra and huawei-push-kit
> more connectors that support scala3

- avroparquet/src/test/scala-2/docs/scaladsl/AbstractAvroParquet.scala
- avroparquet/src/test/scala-3/docs/scaladsl/AbstractAvroParquet.scala
- avroparquet/src/test/scala/docs/scaladsl/AbstractAvroParquetBase.scala
- avroparquet/src/test/scala/docs/scaladsl/AvroParquetFlowSpec.scala
- avroparquet/src/test/scala/docs/scaladsl/AvroParquetSinkSpec.scala
- avroparquet/src/test/scala/docs/scaladsl/AvroParquetSourceSpec.scala
- build.sbt
- docs/src/main/paradox/avroparquet.md
- project/Common.scala
- project/Dependencies.scala
part of https://github.com/apache/incubator-pekko-connectors/issues/126
> support scala3 in avroparquet

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/javadsl/S3.scala
function calls itself recursively infinitely - needs to call another overloaded version of the function
> s3: fix infinite recursion

- ftp/src/test/scala/org/apache/pekko/stream/connectors/ftp/BaseSpec.scala
* the code has no license specified
* if it turns out that we need this test code, we will need to either see if scalatest supports retries now (`eventually` works well)
* or approach the author to see if he will grant us permission to license the gist
> remove code copied from gist

- .github/workflows/check-build-test.yml
- CONTRIBUTING.md
- build.sbt
As can be seen from https://github.com/apache/incubator-pekko-connectors/pull/205#issuecomment-1657823432 users unfamiliar to the codebase are having issues both checking/applying scalafmt and javafmt to the codebase
> Add commands to apply and check codestyle

- NOTICE
- build.sbt
- legal/MqttStreamingLicense.txt
- legal/S3License.txt
- legal/S3Notice.txt
- mqtt-streaming/src/main/scala/org/apache/pekko/stream/connectors/mqtt/streaming/impl/RequestState.scala
- project/MetaInfLicenseNoticeCopy.scala
* also fixes some typos in a recent S3 license/notice PR
* Because paho is dual licensed, I've chosen the more permissive Eclipse Distribution License
* see https://www.apache.org/legal/resolved.html (Eclipse Distribution License is category A while Eclipse Public License is category B).
Fixes https://github.com/apache/incubator-pekko-connectors/issues/184
> add paho license

- project/plugins.sbt
switches to just publishing a tgz release (no zip)
> sbt-source-dist 0.1.10

- project/plugins.sbt
Latest pekko-grpc has a different artifact name for the sbt plugin
> Update to latest pekko-grpc-sbt-plugin snapshot

- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/model.scala
Resolves #216 by adding a method to FtpSettings and FtpsSettings to enable or disable automatic server encoding detection.
> FTP: Add a setting to enable automatic server encoding detection

- build.sbt
Forgot to do this in previous PR
> Add sbt-header to code style checks

- LICENSE
- legal/S3License.txt
- project/Dependencies.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/auth/CanonicalRequest.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/javadsl/S3.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/TestUtils.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/impl/SplitAfterSizeSpec.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/impl/auth/CanonicalRequestSpec.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/impl/auth/SplitAfterSizeWithContextSpec.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/impl/retry/Retry.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/impl/retry/Timeouts.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3WireMockBase.scala
relates to #166 
* have grabbed some code from futiles lib to remove the dependency (which does not yet support scala 3)
* this will need to acknowledged in our license - futiles is Apache licensed
* Scala 3 is stricter about private access and it looks like we'll need to make some pekko-http classes public.
* `Content-Length`   
* `Content-Type`
* char `.toHexString` fails to compile due to https://github.com/lampepfl/dotty/issues/14630 
* A couple more compile problems also
> add scala3 support for s3

- project/Dependencies.scala
Either this may have been missed or we are lucky because the azure-storage-queue compiles with Scala 3 fine
> Add scala3 support to Azure Storage Queue

- build.sbt
- project/plugins.sbt
we still need to have the snapshot resolver because of the pekko-sbt-paradox plugin and pekko-material-theme
> grpc 1.0.0 release

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
this line times out 50% of the time in our CI runs - eg https://github.com/apache/incubator-pekko-connectors/actions/runs/5561095341/jobs/10158693141#step:5:674
see https://github.com/apache/incubator-pekko-connectors/issues/148
> retry mqtt stream test that fails a lot

- build.sbt
We are not relying on snapshots anymore so we can remove the repository
> Remove Apache snapshot repository

- .asf.yaml
Currently the protected tags was setup manually however there is now official support for this in `.asf.yaml` (see https://issues.apache.org/jira/browse/INFRA-24644?focusedCommentId=17728711&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17728711).
Resolves: https://github.com/apache/incubator-pekko-connectors/issues/136. The issue also states why not to merge for now.
> [DO-NOT-MERGE] Add protected tags to .asf.yaml

- elasticsearch/src/main/scala/org/apache/pekko/stream/connectors/elasticsearch/WriteSettingsBase.scala
Scala compiler warns about these imports
> remove unnecessary imports

- project/Dependencies.scala
google-auth-library-oauth2-http uses an old version of Jackson that has CVEs
> upgrade google-auth dependency

- project/Dependencies.scala
I think this was done before but because of  issues when rebasing the scala3 branch the changes were lost. In any case, these comments are unnecessary because sbt-license-report does the same job (and more correctly since it actually scans the dependency tree).
> Remove unnecessary license comments

- project/Dependencies.scala
* try to get orientdb and cassandra connectors to use jackson 2.14.3
* also some jackson modules in geode are behind
* jackson 2.14.3 is what we use in pekko and it has no CVEs
> upgrade jackson version

- docs/src/main/paradox/release-notes/index.md
* RC1 for v1.0.1 should be ready soon
> more details for v1.0.1 release

- project/Dependencies.scala
There was a regression in https://github.com/apache/incubator-pekko-connectors/commit/2b5fcd11937270d0995f788486cb9cc4216067fb#diff-ad2642dc77b3679e4ad2c7d3b2f59a2dcf48c1bf5b93a558a4fa44828315a34cR29 where the Pekko dependencies were set to "current" (likely because a grpc release wasn't made) but in reality its actually meant to be a statically hardcoded version.
You can use https://github.com/mdedetrich/alpakka-apache/blob/4ebf24a4f996b088b4ed16cee182accc5ac92e1c/project/Dependencies.scala#L16-L21 as a reference of how it looked like at last point before fork
>  Properly fix versioning for Pekko dependencies

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/S3Stream.scala
When I originally added this functionality I mistakingly hardcoded the type parameter to `NotUsed` rather than just using `_` (which means don't care). While this may initially seem like a non-issue, a problem eventuates if you happen to use a `Sink` that materializes a value that is contained within a `Future` i.e. `Sink[(UploadPartResponse, immutable.Iterable[C]), Future[Done]]`. Such sinks are quite common and there is no way to get a value outside of a `Future` aside from blocking (which you should never do in production code) in order to satisfy `chunkUploadSink: Sink[(UploadPartResponse, immutable.Iterable[C]), NotUsed]`.
Note that since `chunkUploadSink` ultimately ends up [getting used in `.alsoTo`](https://github.com/apache/incubator-pekko-connectors/blob/18fc2932cf78194ea149bda0d …
> Accept any materializer type param for S3's chunkUploadSink

- cassandra/src/test/java/docs/javadsl/CassandraTestHelper.java
Cassandra tests started failing recently and it isn't clear that any recent change is causing this. I tried reverting the logback upgrade but that didn't help.
This timeout change seems to help.
> increase cassandra test timeout

- .github/workflows/check-build-test.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-pekko-1.1-builds.yaml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-nightly.yml
- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
* need to test with pekko 1.0 and 1.1
> Also test with pekko 1.1

- .github/workflows/nightly-pekko-1.1-builds.yaml
- kinesis/src/test/java/org/apache/pekko/stream/connectors/kinesis/javadsl/KinesisTest.java
clashes with java.lang.Record
causes compile issues if you build with JDK >= 14
> prepend package name for Record class

- kinesis/src/main/scala/org/apache/pekko/stream/connectors/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/test/scala/org/apache/pekko/stream/connectors/kinesis/KinesisFlowSpec.scala
The kinesis throttling is not being respected because the function `getPayloadByteSize` is incorrect. 
```scala
private def getPayloadByteSize[T](record: (PutRecordsRequestEntry, T)): Int = record match {
case (request, _) => request.partitionKey.length + request.data.asByteBuffer.position()
}
```
`request.data.asByteBuffer.position()` can return 0
The ticket was originally reported in https://github.com/akka/alpakka/issues/2871 and I did the fix in the akka repository. AFAICT I can use the same code as long as I am the author...
> Kinesis: fix maxBytesPerSecond throttling

- project/Common.scala
We have long since removed the concept of formatting sources on compile in all of the Pekko modules, furthermore setting these settings are redundant anyways since they default to `false` anyways.
> Remove redundant formatting sbt settings

- ftp/src/test/resources/sftpd/init.sh
@Claudenw requested that we document this file.
https://lists.apache.org/thread/7p1k49ytrwknbcyjwnj0jo1o00z4hnlw
This file is used in our automated tests. We use docker-compose to start an FTP server and a Squid Proxy server.
https://github.com/apache/incubator-pekko-connectors/blob/a639063ffc41a9cb8f9ba5c11dfd997a6750b3c1/docker-compose.yml#L235
> add warning to init.sh

- build.sbt
- project/plugins.sbt
Updates sbt-pekko-build to 0.3.1 which brings in the pom.xml `name` field fix
> Update sbt-pekko-build to 0.3.1

- project/Dependencies.scala
- project/PekkoHttpDependency.scala
Just like with pekko core, adds a dynamic dependency for pekko-http to pekko-connectors so we make sure that pekko-connectors continue to work against new versions of pekko-http (connectors uses pekko-http heavily so we should be doing this).
> Add PekkoHttpDependency from sbt-pekko-build

- .asf.yaml
- .github/workflows/nightly-pekko-1.1-builds.yaml
- .github/workflows/publish-1.0-docs.yml
also updates job for 1.0 doc publishing to use v1.0.2 (latest release)
> protect 1.0.x branch

- project/Dependencies.scala
Upgrade amqp-client to 5.20.0 due to CVE-2023-46120
details are given at: https://deps.dev/advisory/osv/GHSA-mm8h-8587-p46h
If I should create an issue, let me create and associate it with this issue.
> Update amqp-client to 5.20.0

- build.sbt
we are getting issues in `main` branch builds with mima checks - since the v1.1.0-M0 git tag was added
see https://github.com/apache/incubator-pekko-connectors/actions/runs/7678675966/job/20928810106
the issue is because the current setup uses the git tags and expects there to be releases for every git tag
We can test with "1.0.2" for the time being
I raised https://github.com/sbt/sbt-dynver/issues/283 to possibly do a change there so that we could go back to using the `previousStableVersion` sbt variable.
> mima compare version

- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/jwt/JwtSprayJson.scala
- project/Dependencies.scala
- sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
lib used in security - seems best to keep it updated
> upgrade jwt-scala

- project/Dependencies.scala
* may not be that useful - I thought aws sdk used netty but it seems to just use it in test cases
* still may be useful to upgrade but maybe only in pekko-connectors 1.1.0
> upgrade aws libs

- google-cloud-pub-sub/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/model.scala
- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStream.scala
- google-common/src/main/resources/reference.conf
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/Credentials.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/ServiceAccountCredentials.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/auth/GoogleOAuth2Spec.scala
- google-fcm/src/main/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/impl/FcmFlows.scala
While working on https://github.com/apache/incubator-pekko-connectors/pull/313 I realized that we have duplicate scope configuration settings, i.e. one [here](https://github.com/apache/incubator-pekko-connectors/blob/1fe3474d654bf48b0e81011d878e541a32409c93/google-common/src/main/resources/reference.conf#L9) and another [here](https://github.com/apache/incubator-pekko-connectors/blob/1fe3474d654bf48b0e81011d878e541a32409c93/google-common/src/main/resources/reference.conf#L31-L32).
This PR removes the scopes config [here](https://github.com/apache/incubator-pekko-connectors/blob/1fe3474d654bf48b0e81011d878e541a32409c93/google-common/src/main/resources/reference.conf#L31-L32) and instead makes the `ServiceAccountCredentials` use the scopes value from …
> Remove duplicate scopes value in reference.conf

- elasticsearch/src/main/scala/org/apache/pekko/stream/connectors/elasticsearch/ElasticsearchConnectionSettings.scala
This PR is a response to https://github.com/apache/incubator-pekko/pull/894, specifically rather than using the Java designed converter methods within Scala sources we use the Scala ones so that when the project is compiled with Scala 3 it gets inlined.
> Use designated Scala methods for converter utils

- .github/workflows/format.yml
So that scalafmt picks the right branch
> Update scalafmt reference to 1.0.x

- docs/src/main/paradox/data-transformations/xml.md
- google-cloud-bigquery/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/scaladsl/BigQueryTableData.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/util/AnnotateLast.scala
- xml/src/test/java/docs/javadsl/XmlParsingTest.java
- xml/src/test/scala/docs/scaladsl/XmlProcessingSpec.scala
Motivation:
Make use of statefulMap
> chore: Make use of statefulMap instead.

- project/Dependencies.scala
we can repurpose #394 to examine why sqs is not working with newer aws jars
> fix sqs build

- build.sbt
Enable the inliner since this is now 1.1.x. @pjfanning I know you were sensitive about explicitly setting this to `true` to make it more clear but doing so disables the knob/cli flag at https://github.com/pjfanning/sbt-pekko-build/blob/main/src/main/scala/com/github/pjfanning/pekkobuild/PekkoInlinePlugin.scala#L56 and I don't think explicitly setting `pekkoInlineEnabled` is having much of an effect either way on developers.
If you still want me to explicitly set it to `true` then let me know and ill update the PR.
> Enable inliner

- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-pekko-1.1-builds.yaml
Motivation:
Do it at 1 AM everyday, then we can check the snapshot just after the pekko-core snapshot published.
> chore: Do nightly build at 3 AM.

- .scala-steward.conf
- project/Dependencies.scala
Hadoop 3.4.0 is only just being released. I think it is safer to target Hadoop 3.3 for now.
> use hadoop 3.3.6 (hdfs connector)

- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/ComputeEngineCredentials.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/Credentials.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/GoogleComputeMetadata.scala
Currently when getting Google credentials using the `ComputeEngineCredentials` method, it ignores the [`scopes`](https://github.com/apache/incubator-pekko-connectors/blob/1fe3474d654bf48b0e81011d878e541a32409c93/google-common/src/main/resources/reference.conf#L9) variable.
In the official Google SDK, you can see that it also has the same logic for getting the credentials from `ComputeEngine`, see https://github.com/googleapis/google-auth-library-java/blob/a7a8d7a4102b0b7c1b83791947ccb662f060eca7/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L193-L199 and https://github.com/googleapis/google-auth-library-java/blob/a7a8d7a4102b0b7c1b83791947ccb662f060eca7/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L480-L483 (which is the same URI as …
> Use scope config for compute-engine auth

- project/Dependencies.scala
* latest kudu libs cause us build problems
* idea is to upgrade to 1.10.1 and investigate further upgrades after that
* I can build with versions newer than 1.10.1 (up to 1.14.0) but the tests fail with 
```
[org.apache.pekko.stream.connectors.kudu.impl.KuduFlowStage$$anon$1-KuduFLow]: the number of replicas does not equal the number of servers
java.lang.IllegalArgumentException: the number of replicas does not equal the number of servers
at org.apache.kudu.shaded.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
at org.apache.kudu.client.RemoteTablet.<init>(RemoteTablet.java:78)
at org.apache.kudu.client.AsyncKuduClient.discoverTablets(AsyncKuduClient.java:2412)
at org.apache.kudu.client.AsyncKuduClient$MasterLookupCB.call(AsyncKuduClient.java:2291)
at …
```
> use kudu 1.10.1 libs

- project/Dependencies.scala
The datastax driver has been donated to the ASF. The 4.18.0 release does not seem to have any significant changes from 4.17.0 (last datastax release). Even the package names in the code haven't changed yet.
The excludes in the sbt have no effect because the transitive dependencies are optional.
see https://github.com/apache/incubator-pekko-connectors/issues/202
> use apache cassandra driver

- NOTICE
- ftp/src/main/java/org/apache/pekko/stream/connectors/ftp/impl/LegacyFtpsClient.java
- ftp/src/main/mima-filters/1.1.x.backwards.excludes/ftpsclient.backwards.excludes
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpLike.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/model.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/org/apache/pekko/stream/connectors/ftp/FtpsWithProxyStageTest.java
- project/Dependencies.scala
see #169 
Remaining work
* add config to allow commons-net FTPSClient to be used
* add FTP NOTICE file to connectors-ftp jar
* the LegacyFtpsClient can be greatly simplified after commons-net 3.11.0 is released - we can subclass commons-net FTPSClient and just override one method - https://github.com/apache/commons-net/pull/204 makes the state that we need accessible
> upgrade commons-net to 3.10.0 due to cve

- .scala-steward.conf
We can still use sbt-paradox/sbt-paradox-project-info, just needs to be 0.9.x series
> Move sbt-paradox to pinned updates

- project/plugins.sbt
The previous [PR](https://github.com/apache/incubator-pekko-connectors/pull/536) forgot to fix the excludes for `sbt-site-paradox`.
Ordinarily we would fix this in https://github.com/apache/incubator-pekko-sbt-paradox/blob/main/build.sbt#L76-L88 however it seems to be only pekko-connectors that uses `sbt-site-paradox` and since its an sbt plugin that [automatically loads](https://github.com/sbt/sbt-site/blob/main/core/src/main/scala/com/typesafe/sbt/site/SitePlugin.scala#L9) adding it to pekko-sbt-paradox isn't appropriate (this is also the reason why we have cases in pekko-connectors where the plugin is [explicitly disabled](https://github.com/apache/incubator-pekko-connectors/blob/main/build.sbt#L22))
> Fix excludes for sbt-site-paradox

- project/plugins.sbt
Backporting the latest pekko-sbt-paradox fixes. This is necessary due to the github api rate limiting issue so it also needs to be fixed for 1.0.x
> Update sbt pekko paradox

- scripts/link-validator.conf
Due to https://github.com/apache/incubator-pekko-connectors/pull/517, will also need to be backported after https://github.com/apache/incubator-pekko-connectors/pull/555 is merged
> Update link-validator.conf due to Scala 2.13.13

- .scala-steward.conf
problems in jackson 2.17 include
* perf issues due to change in buffer recycler default
* bug when parsing numbers that have no digit before the decimal point
* stray compile dependency on bytebuffer - should have been test scope
> stick with jackson 2.16

- build.sbt
see https://github.com/apache/pekko-connectors/actions/runs/8446006883/job/23134119754
no longer need to access staging jars
> need build to be able to access snapshot jars

- .scala-steward.conf
- docker-compose.yml
- project/Dependencies.scala
using latest docker image allows us to upgrade the sqs lib
see #523
> upgrade sqs lib

- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/jwt/JwtSprayJson.scala
* this code is not taken from Akka - so it shouldn't have the Akka specific license header
* the original code is Apache licensed
> update license header

- s3/src/test/scala/org/apache/pekko/stream/connectors/s3/MinioContainer.scala
getHost replaces getContainerIpAddress
https://github.com/testcontainers/testcontainers-java/issues/4715
> testcontainers deprecated method warning

- project/Dependencies.scala
see https://github.com/apache/pekko-management/pull/208
aim is to reduce the number of security issues listed in https://github.com/apache/pekko-connectors/security/dependabot
> upgrade wiremock and its dependencies due to CVEs

- build.sbt
- project/plugins.sbt
We have BOMs for Pekko(Core) and Pekko-HTTP.
* https://repo1.maven.org/maven2/org/apache/pekko/pekko-bom_2.13/1.0.2/pekko-bom_2.13-1.0.2.pom
* https://repo1.maven.org/maven2/org/apache/pekko/pekko-http-bom_2.13/1.0.1/pekko-http-bom_2.13-1.0.1.pom
I think it useful to have one for Pekko-Connectors.
> add pekko-connectors-bom

- .scala-steward.conf
Newer versions of jetty need java 11
> pin jetty in .scala-steward.conf

- file/src/main/scala/org/apache/pekko/stream/connectors/file/impl/archive/ZipArchiveFlow.scala
- file/src/test/java/docs/javadsl/ArchiveHelper.java
ByteString unsafe functions should only be used if you know if other code can mutate the arrays
> zip: use ByteString conversions because we know they are safe in this case

- google-cloud-bigquery-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/storage/scaladsl/BigQueryStorage.scala
the byte array passed in is safe (not reused)
> bigquery: use fromArrayUnsafe

- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/DiskBuffer.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/auth/Signer.scala
- s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/auth/package.scala
the 'unsafe' methods are ok if you know the data is not being mutated
> s3: avoid array copies when dealing with ByteStrings

- docs/src/main/paradox/ftp.md
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/model.scala
- ftp/src/main/scala/org/apache/pekko/stream/connectors/ftp/scaladsl/FtpApi.scala
More commonly called FTPS as opposed to FTPs - the latter can be mistaken for a plural of FTP.
https://en.wikipedia.org/wiki/FTPS
> refer to FTPS

- build.sbt
- google-cloud-pub-sub-grpc/src/main/mima-filters/1.1.x.backwards.excludes/io.grpc.backwards.excludes
- project/Dependencies.scala
- project/plugins.sbt
we have changed the main branch on our other repos to use Pekko 1.1 - updating connectors now that gRPC 1.1.0-M1 is released
> build with pekko grpc 1.1

- text/src/main/scala/org/apache/pekko/stream/connectors/text/impl/CharsetDecodingFlow.scala
- text/src/main/scala/org/apache/pekko/stream/connectors/text/javadsl/TextFlow.scala
- text/src/main/scala/org/apache/pekko/stream/connectors/text/scaladsl/TextFlow.scala
- text/src/test/java/docs/javadsl/CharsetCodingFlowsDoc.java
More direct and simple implementation
> Improve implement for pekko-connectors-text

- docs/src/main/paradox/couchbase.md
- project/project-info.conf
relates to https://github.com/apache/pekko-connectors/issues/623
we need fuller docs but at least this mentions the alternative connector
> add stub doc for couchbase3 client

- jakartams/src/main/resources/reference.conf
- jakartams/src/main/scala/org/apache/pekko/stream/connectors/jakartams/impl/JmsAckSourceStage.scala
- jakartams/src/main/scala/org/apache/pekko/stream/connectors/jakartams/impl/JmsTxSourceStage.scala
I'm not sure that I like keeping the Jms prefix in the new class names for #718 but the API is jakarta.jms so it isn't inaccurate.
This PR just has a few fairly cosmetic changes to differentiate from the pre-existing JMS connector
> some small jakarta ms branding changes

- build.sbt
> fix: disable -Werror for 'file' on Java 21 CI

- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
While looking into #468, I noticed the two failing tests were sharing the same session id, which reminded of #456.
While in this case the two tests aren't sharing the same session, and I haven't investigated the details of this codebase further, I'm curious to see if the problem remains when we use unique session ids.
> fix: don't use overlapping session ids in MqttFlowTest

- .scala-steward.conf
As those versions are managed by a single variable in our build
> chore: avoid scala-steward opening multiple PRs for Jackson

- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
> fix: avoid client id's overlapping between MqttFlowTest and MqttFlowSpec

- docs/src/main/paradox/release-notes/releases-1.1.md
see https://pekko.apache.org/docs/pekko-connectors/1.1/release-notes/releases-1.1.html
It seems that bullet point lists need to have a blank line before them if the previous line is not a header.
> add whitespace to releases-1.1.md due to formatting issues

- geode/src/main/scala-3/org/apache/pekko/stream/connectors/geode/impl/pdx/LabelledGenericGeneric.scala
Makes `LabelledGeneric.productInst` a `transparent inline` to allow consuming it on Scala 3.4+ due to new constraints introduced by the compiler - see https://github.com/scala/scala3/pull/19253 for more details and https://github.com/scala/scala3/issues/21236 for minimization of problem found in this project. 
Without this change users are forced to use `-source:3.3` option when building on Scala 3.4 or later.
The problem was found by the Scala 3 Open Community Build - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/9915156118/job/27395911414)
> Fix`geode` `PdxEncoder/Decoder` derivation on Scala 3.4+

- aws-spi-pekko-http/src/main/scala/org/apache/pekko/stream/connectors/awsspi/RequestRunner.scala
- sqs/src/main/scala/org/apache/pekko/stream/connectors/sqs/SqsSourceSettings.scala
compile warning in build:
```
[warn] /code/incubator-pekko-connectors/aws-spi-pekko-http/src/main/scala/org/apache/pekko/stream/connectors/awsspi/RequestRunner.scala:36:32: parameter sys in class RequestRunner is never used
[warn] class RequestRunner()(implicit sys: ActorSystem, ec: ExecutionContext, mat: Materializer) {
[warn]    
```
aws-spi-pekko-http is a new module in Pekko 1.1 so I think it is ok to remove this implicit param.
> aws-spi-pekko-http: remove unnecessary implicit

- .github/workflows/check-build-test.yml
- build.sbt
- docker-compose.yml
- docs/src/main/paradox/aws-event-bridge.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- docs/src/main/paradox/mqtt.md
- scripts/ftp-servers.sh
see https://github.com/orgs/community/discussions/116610
version param in yml is also deprecated
> fix docker-compose CI issues

- sqs/src/main/scala/org/apache/pekko/stream/connectors/sqs/scaladsl/SqsPublishFlow.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
Add missing `delaySeconds` property in the mapping from `SendMessageRequest` to `SendMessageBatchRequestEntry`
Fixes #759
> SQS - Add delaySeconds to SQS batch publishing

- .github/workflows/check-build-test.yml
- build.sbt
- docker-compose.yml
- docs/src/main/paradox/aws-event-bridge.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- docs/src/main/paradox/mqtt.md
- scripts/ftp-servers.sh
cherry pick 7f8736a6c96c54668038434b2c524ab15360ad2c #764
> docker-compose changes (#764)

- project/Dependencies.scala
This updates fixes critical bug, see https://github.com/mdedetrich/pekko-streams-circe/pull/93 and https://github.com/apache/pekko-http/issues/595.
Release notes are here https://github.com/mdedetrich/pekko-streams-circe/releases/tag/v1.1.0
> Update Pekko Stream Circe to 1.1.0

- project/Dependencies.scala
- project/PekkoCoreDependency.scala
- project/PekkoHttpDependency.scala
- project/build.properties
- project/plugins.sbt
* Latest 1.0.x pekko releases
* upgrade some sbt plugins
* some minor bumps in other dependencies (just looking at patch level version bumps)
I got these suggestions from sbt-updates plugin
```
[info] No dependency updates found for pekko-connectors-root
[info] Found 2 dependency updates for pekko-connectors-reference
[info]   org.apache.pekko:pekko-stream : 1.0.2   -> 1.0.3   -> 1.1.0
[info]   org.scala-lang:scala-library  : 2.13.13 -> 2.13.14         
[info] Found 5 dependency updates for pekko-connectors-doc-examples
[info]   org.apache.pekko:pekko-slf4j               : 1.0.2   -> 1.0.3   -> 1.1.0
[info]   org.apache.pekko:pekko-stream              : 1.0.2   -> 1.0.3   -> 1.1.0
[info]   org.apache.pekko:pekko-stream-testkit:test : 1.0.2   -> 1.0.3   -> 1.1.0
[info] …
```
> upgrade sbt, pekko and some minor lib bumps

- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
In https://github.com/apache/pekko-connectors/pull/799 the erorr message was improved, and i can report that it is actually working with my original expectations, and by that I mean that even the `detail` part of the error message is being reported (@raboof was right, the printing of the `detail` part is a configuration setting and its looking like its using sane default values).
As an example, right now the error message is looking like
```
java.util.concurrent.CompletionException: org.apache.pekko.stream.connectors.google.ResumableUpload$InvalidResponseException: Resumable upload failed with status: 403 Forbidden: body: {"error":{"code":403,"message":"<REDACTED> does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on …
```
> Fix error message for ResumableUpload

- build.sbt
- project/Dependencies.scala
* the main branch is intended for 1.1 release and is best to direct specifically to 1.1 docs of other pekko modules
* I intend to backport this to 1.0 branch because that branch needs to direct towards 1.0 versions of other pekko module docs
> don't use 'current' for doc links

- aws-spi-pekko-http/src/main/scala/org/apache/pekko/stream/connectors/awsspi/PekkoHttpClient.scala
- aws-spi-pekko-http/src/main/scala/org/apache/pekko/stream/connectors/awsspi/RequestRunner.scala
- aws-spi-pekko-http/src/test/java/org/apache/pekko/stream/connectors/awsspi/s3/S3Test.java
- aws-spi-pekko-http/src/test/resources/logback-test.xml
- aws-spi-pekko-http/src/test/scala/org/apache/pekko/stream/connectors/awsspi/PekkoHttpClientH1TestSuite.scala
- aws-spi-pekko-http/src/test/scala/org/apache/pekko/stream/connectors/awsspi/RequestRunnerSpec.scala
- project/Dependencies.scala
- project/plugins.sbt
depends on #827 
There is a junit test suite in AWS SDK that might be useful to test the PekkoHttpClient
> add SdkAsyncHttpClientH1TestSuite

- build.sbt
You can test pekko snapshots still by using the [sbt-pekko-build](https://github.com/pjfanning/sbt-pekko-build) system properties
> remove snapshot resolver

- build.sbt
Reverts apache/pekko-connectors#875
This broke https://github.com/apache/pekko-connectors/actions/runs/11528373543/job/32095426830
Looks like sbt-pekko-build only adds the snapshot resolver implicitly if you use addPekkoModuleDependency
The PR that tried to do that was running into build issues that I don't yet have a cause for. https://github.com/apache/pekko-connectors/pull/860
> Revert "remove snapshot resolver"

- .github/workflows/publish-1.1-docs.yml
- docs/src/main/paradox/release-notes/releases-1.1.md
> v1.1.0 release notes

- .jvmopts
running into issues trying to build a release on my laptop
> increase build memory

- .github/workflows/check-build-test.yml
GitHub CI have requested generally that ASF projects avoid running more than 15 jobs in parallel. This CI jobs has a few other jobs as well as the matrix jobs, that's why I choose 10 as the limit here.
> CI: restrict number of parallel jobs

- .scala-steward.conf
As 0.20 requires Java 11
Replaces https://github.com/apache/pekko-connectors/pull/978
> chore: pin hoverfly-java to 0.19

- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GoogleGCStorageStreamIntegrationSpec.scala
This PR replaces the ScalaTest `ignore` directive with `DoNotDiscover` which is whats used with AWS (see https://github.com/apache/pekko-connectors/blob/8c5d65051cfeb3df4a0eb87039c33131b6b21ccc/s3/src/test/scala/org/apache/pekko/stream/connectors/s3/scaladsl/S3IntegrationSpec.scala#L1281). The `DoNotDiscover` annotation means that the test won't be run when you run the general `test` command in sbt however it can be run with an explicit command as well as supporting running in Intellij directly (see comment) .
The PR also splits out the test into its implementation (the trait) and the runner (the class). The intention here is to run the integration spec against [fake-gcs-server](https://github.com/fsouza/fake-gcs-server) (in the same way that we have S3 tests that are run against minio).
> Replace ignore with DoNotDiscover and split test out

- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GoogleGCStorageStreamIntegrationSpec.scala
In addition to getting rid of the depreciation message, this is necessary to add in [fake-gcs-server](https://github.com/fsouza/fake-gcs-server) testing as only `GoogleSettings` has the necessary `settings.withCredentials(NoCredentials(projectId, ""))` method (the deprecated `GCStorageSettings` has no such method and hence it forces official google authentication which won't work with gcs-storage-settings)
I have verified this hasn't caused any regressions by testing against a real google account. Another easy way to verify is to temporarily make `ServiceAccountCredentials` public, as well as the various constructor parameters and then you can do
```scala
val credentials = settings.credentials.asInstanceOf[org.apache.pekko.stream.connectors.google.auth.ServiceAccountCredentials] …
```
> Use GoogleSettings instead of GCStorageSettings

- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GoogleGCStorageStreamIntegrationSpec.scala
Currently the gcs tests don't even use the defined `GoogleSettings`, this PR fixes that. It also adds `GCSSettings` which is also used by google cloud storage tests.
This is a follow on from https://github.com/apache/pekko-connectors/pull/1020
> Actually use attributes in GCS tests

- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/http/GoogleHttp.scala
When working on adding tests that run on [fake-gcs-server](https://github.com/fsouza/fake-gcs-server) I programmatically configure `GoogleSettings` rather than having it resolve via typesafe config since I am using testcontaines with dynamic values for the host (this is follow up from https://github.com/apache/pekko-connectors/pull/1020 and https://github.com/apache/pekko-connectors/pull/1022).
I stumbled upon tests failing due to them resolving `GoogleSettings` via [`application.conf`](https://github.com/apache/pekko-connectors/blob/1fe3474d654bf48b0e81011d878e541a32409c93/google-cloud-storage/src/test/resources/application.conf) even though I was explicitly trying to bypass this type of typesafe config loading i.e.
```scala
lazy val googleSettings =
GoogleSettings.create( …
```
> Properly propogate GoogleSettings in addStandardQuery

- google-cloud-storage/src/test/resources/application.conf
With the result of https://github.com/apache/pekko-connectors/pull/1020 and https://github.com/apache/pekko-connectors/pull/1022 these settings are no longer being used/loaded in the test code
> Remove old leftover test settings

- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GoogleGCStorageStreamIntegrationSpec.scala
This as as per instructions at https://github.com/apache/pekko-connectors/blob/7b5878e46ee76b39619b92b1175e1af40af0eccf/google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GoogleGCStorageStreamIntegrationSpec.scala#L35
> Bucket name should be pekko-connectors

- google-cloud-storage/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/scaladsl/GCStorageWiremockBase.scala
Resolves https://github.com/apache/pekko-connectors/issues/656 .
Underlying issue is that metadata needs to be nested inside of its own "metadata" object, see https://cloud.google.com/storage/docs/json_api/v1/objects/insert#request-body
With this test, running `sbt "google-cloud-storage/Test/runMain org.scalatest.tools.Runner -o -s org.apache.pekko.stream.connectors.googlecloud.storage.impl.GoogleGCStorageStreamIntegrationSpec"` against an actual  google cloud account works.
> Fix metadata not working with GCStorage

- project/Dependencies.scala
scala-steward seems not to be creating PRs to upgrade this lib. We don't seem to have anything in the .scala-steward.conf for log4j.
> log4j 2.24.3

- google-cloud-storage/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
- google-common/src/main/mima-filters/1.1.x.backwards.excludes/private-zero-chunk-change.backwards.excludes
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/ResumableUpload.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/util/AnnotateLast.scala
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/util/AnnotateLastSpec.scala
Resolves: https://github.com/apache/pekko-connectors/issues/1054
This PR solves resumable upload for gcs when uploading an empty payload (i.e. zero bytes).  Comments have been added explaining how the solution works, but in short a special sentinel value gets inserted in the `onComplete` of `statefulMap` where the chunks get calculated on the specific case that the state is empty (which means nothing is being processed, hence empty payload) and this sentinel value gets used/detected later when calculating the Content-Range header.
A test has been added to confirm that this works, without this change the newly added test fails. I also rerun the entire test suite against a real GCS account to make sure there are no additional regressions.
@He-Pin Would be good if you check this PR as you …
> Make GCS resumableUpload work with empty byte payload

- .scala-steward.conf
Failures in CI because we can't have Scala Steward upgrade CI actions (due to how ASF configure our repos)
https://github.com/apache/pekko-connectors/actions/runs/15950739121
Easier at the moment to manage pekko upgrades using manual PRs.
The Scala Steward failures are blocking us from getting PRs for some other libs that are already out of date.
> Manage Pekko upgrades explicitly

- google-cloud-bigquery-storage/src/main/resources/reference.conf
- google-cloud-bigquery/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/bigquery/scaladsl/BigQueryQueriesSpec.scala
- google-cloud-pub-sub/src/test/resources/application.conf
- google-cloud-pub-sub/src/test/scala/org/apache/pekko/stream/connectors/google/AuthorizationHeaderSpec.scala
- google-cloud-pub-sub/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/PubSubMockSpec.scala
- google-cloud-pub-sub/src/test/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/impl/PubSubApiSpec.scala
- google-common/src/main/resources/reference.conf
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/AccessTokenCredentials.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/Credentials.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/auth/OAuth2Credentials.scala
- google-common/src/main/scala/org/apache/pekko/stream/connectors/google/http/GoogleHttp.scala
- google-common/src/test/resources/application.conf
- google-common/src/test/scala/org/apache/pekko/stream/connectors/google/http/GoogleHttpSpec.scala
- google-fcm/src/test/scala/org/apache/pekko/stream/connectors/google/firebase/fcm/v1/impl/FcmSenderSpec.scala
This PR modifies `NoCredentials` so that you aren't forced to provide it with a token and by consequence means that no `Authorization` header will be added when using `NoCredentials`. More specifically, the constructor for `NoCredentials` has been changed so that it doesn't have a `token` parameter and the `token` value from typesafe config is no longer retrieved.
In order to get this to work, I had to split out the `get()` method (which returns the token) from `Credentials` into a separate `RetrievableCredentials` trait and every subclass of `Credentials` aside from `NoCredentials` inherits this trait.
The main reason for this change is that `NoCredentials` shouldn't, by design, add token auth headers (the official analogue from Google's own sdk [doesn't do …
> Rename none credentials to access-token and remove token from none

- .github/workflows/check-build-test.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-pekko-1.0-builds.yaml
- .github/workflows/nightly-pekko-1.2-builds.yaml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
* we've seen at least 1 bin compat issue with Pekko 1.2.0
* we don't really need to test pekko 1.0.x nightly
* update action versions
* change the nightly tests to test the 1.2.x branch as we need a 1.2.0 release but little point testing main branch yet because we are making breaking changes
> test with pekko 1.2.x
